name: Generate Snake Animation

on:
  # 每天 UTC 时间 0 点运行
  schedule:
    - cron: "0 0 * * *"
  
  # 允许手动触发
  workflow_dispatch:
  
  # 每次 push 到 main 分支时运行
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout 代码
      - name: Checkout
        uses: actions/checkout@v3

      # 生成贪吃蛇图
      - name: Generate contribution snake assets
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # 推送到 output 分支
      - name: Push github-contribution-grid-snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}